name: caching 

on:
   push:
   workflow_dispatch:
      input:
         use-cache:
            description: whether to execute cache step
            type: boolean
            default: true
jobs:
   build:
       runs-on: ubuntu-latest
       steps:
         -name: checkout code
          uses: actions/checkout@v4
         -name: set node
          uses: actions/setup-node@v3
          with:
            node-version: '20.x'
         -name: install dependencies
          run: npm ci
         -name: testing
          run: npm run test
         -name: building
          run: npm run build
         -name: deploying to nonprod
          run: echo "deploying to nonprod"


       
